// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tpl.Api.Models;

namespace Tpl.Api.Migrations
{
    [DbContext(typeof(TPLContext))]
    [Migration("20201114162633_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CarManufacturerCarModel", b =>
                {
                    b.Property<int>("CarManufacturersId")
                        .HasColumnType("int");

                    b.Property<int>("CarModelsId")
                        .HasColumnType("int");

                    b.HasKey("CarManufacturersId", "CarModelsId");

                    b.HasIndex("CarModelsId");

                    b.ToTable("CarManufacturerCarModel");
                });

            modelBuilder.Entity("Tpl.Api.Models.Db_Models.CarFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CarModelId")
                        .HasColumnType("int");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ReleaseTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TplModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CarFeatures");
                });

            modelBuilder.Entity("Tpl.Api.Models.Db_Models.CarManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("CarManufacturers");
                });

            modelBuilder.Entity("Tpl.Api.Models.Db_Models.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CarFeatureId")
                        .HasColumnType("int");

                    b.Property<int>("CarManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CarFeatureId");

                    b.ToTable("CarModels");
                });

            modelBuilder.Entity("Tpl.Api.Models.Db_Models.PersonalInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdentityImg")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PersonalNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("TplModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PersonalInformations");
                });

            modelBuilder.Entity("Tpl.Api.Models.Db_Models.TplLimit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Bonus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Limit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TplModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TplModelId");

                    b.ToTable("TplLimits");
                });

            modelBuilder.Entity("Tpl.Api.Models.Db_Models.TplModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CarFeatureId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonalInformationId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("TplImitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarFeatureId");

                    b.HasIndex("PersonalInformationId");

                    b.ToTable("TplModels");
                });

            modelBuilder.Entity("CarManufacturerCarModel", b =>
                {
                    b.HasOne("Tpl.Api.Models.Db_Models.CarManufacturer", null)
                        .WithMany()
                        .HasForeignKey("CarManufacturersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tpl.Api.Models.Db_Models.CarModel", null)
                        .WithMany()
                        .HasForeignKey("CarModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tpl.Api.Models.Db_Models.CarModel", b =>
                {
                    b.HasOne("Tpl.Api.Models.Db_Models.CarFeature", null)
                        .WithMany("CarModels")
                        .HasForeignKey("CarFeatureId");
                });

            modelBuilder.Entity("Tpl.Api.Models.Db_Models.TplLimit", b =>
                {
                    b.HasOne("Tpl.Api.Models.Db_Models.TplModel", null)
                        .WithMany("TplImits")
                        .HasForeignKey("TplModelId");
                });

            modelBuilder.Entity("Tpl.Api.Models.Db_Models.TplModel", b =>
                {
                    b.HasOne("Tpl.Api.Models.Db_Models.CarFeature", null)
                        .WithMany("TplModels")
                        .HasForeignKey("CarFeatureId");

                    b.HasOne("Tpl.Api.Models.Db_Models.PersonalInformation", null)
                        .WithMany("TplModels")
                        .HasForeignKey("PersonalInformationId");
                });

            modelBuilder.Entity("Tpl.Api.Models.Db_Models.CarFeature", b =>
                {
                    b.Navigation("CarModels");

                    b.Navigation("TplModels");
                });

            modelBuilder.Entity("Tpl.Api.Models.Db_Models.PersonalInformation", b =>
                {
                    b.Navigation("TplModels");
                });

            modelBuilder.Entity("Tpl.Api.Models.Db_Models.TplModel", b =>
                {
                    b.Navigation("TplImits");
                });
#pragma warning restore 612, 618
        }
    }
}
