// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tpl.Api.Models;

namespace Tpl.Api.Migrations
{
    [DbContext(typeof(TPLContext))]
    partial class TPLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Tpl.Api.Models.Db_Models.CarFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CarModelId")
                        .HasColumnType("int");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ReleaseTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TplModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CarFeatures");
                });

            modelBuilder.Entity("Tpl.Api.Models.Db_Models.CarManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("CarManufacturers");
                });

            modelBuilder.Entity("Tpl.Api.Models.Db_Models.CarManufacturerCarModel", b =>
                {
                    b.Property<int>("CarManufacturersId")
                        .HasColumnType("int");

                    b.Property<int>("CarModelsId")
                        .HasColumnType("int");

                    b.HasKey("CarManufacturersId", "CarModelsId");

                    b.HasIndex(new[] { "CarModelsId" }, "IX_CarManufacturerCarModel_CarModelsId");

                    b.ToTable("CarManufacturerCarModel");
                });

            modelBuilder.Entity("Tpl.Api.Models.Db_Models.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CarFeatureId")
                        .HasColumnType("int");

                    b.Property<int>("CarManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CarFeatureId" }, "IX_CarModels_CarFeatureId");

                    b.ToTable("CarModels");
                });

            modelBuilder.Entity("Tpl.Api.Models.Db_Models.PersonalInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdentityImg")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PersonalNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("TplModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PersonalInformations");
                });

            modelBuilder.Entity("Tpl.Api.Models.Db_Models.TplLimit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Bonus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Limit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TplModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TplModelId" }, "IX_TplLimits_TplModelId");

                    b.ToTable("TplLimits");
                });

            modelBuilder.Entity("Tpl.Api.Models.Db_Models.TplModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CarFeatureId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("PersonalInformationId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("TplImitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CarFeatureId" }, "IX_TplModels_CarFeatureId");

                    b.HasIndex(new[] { "PersonalInformationId" }, "IX_TplModels_PersonalInformationId");

                    b.ToTable("TplModels");
                });

            modelBuilder.Entity("Tpl.Api.Models.Db_Models.CarManufacturerCarModel", b =>
                {
                    b.HasOne("Tpl.Api.Models.Db_Models.CarManufacturer", "CarManufacturers")
                        .WithMany("CarManufacturerCarModels")
                        .HasForeignKey("CarManufacturersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tpl.Api.Models.Db_Models.CarModel", "CarModels")
                        .WithMany("CarManufacturerCarModels")
                        .HasForeignKey("CarModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarManufacturers");

                    b.Navigation("CarModels");
                });

            modelBuilder.Entity("Tpl.Api.Models.Db_Models.CarModel", b =>
                {
                    b.HasOne("Tpl.Api.Models.Db_Models.CarFeature", "CarFeature")
                        .WithMany("CarModels")
                        .HasForeignKey("CarFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarFeature");
                });

            modelBuilder.Entity("Tpl.Api.Models.Db_Models.TplLimit", b =>
                {
                    b.HasOne("Tpl.Api.Models.Db_Models.TplModel", "TplModel")
                        .WithMany("TplLimits")
                        .HasForeignKey("TplModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TplModel");
                });

            modelBuilder.Entity("Tpl.Api.Models.Db_Models.TplModel", b =>
                {
                    b.HasOne("Tpl.Api.Models.Db_Models.CarFeature", "CarFeature")
                        .WithMany("TplModels")
                        .HasForeignKey("CarFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tpl.Api.Models.Db_Models.PersonalInformation", "PersonalInformation")
                        .WithMany("TplModels")
                        .HasForeignKey("PersonalInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarFeature");

                    b.Navigation("PersonalInformation");
                });

            modelBuilder.Entity("Tpl.Api.Models.Db_Models.CarFeature", b =>
                {
                    b.Navigation("CarModels");

                    b.Navigation("TplModels");
                });

            modelBuilder.Entity("Tpl.Api.Models.Db_Models.CarManufacturer", b =>
                {
                    b.Navigation("CarManufacturerCarModels");
                });

            modelBuilder.Entity("Tpl.Api.Models.Db_Models.CarModel", b =>
                {
                    b.Navigation("CarManufacturerCarModels");
                });

            modelBuilder.Entity("Tpl.Api.Models.Db_Models.PersonalInformation", b =>
                {
                    b.Navigation("TplModels");
                });

            modelBuilder.Entity("Tpl.Api.Models.Db_Models.TplModel", b =>
                {
                    b.Navigation("TplLimits");
                });
#pragma warning restore 612, 618
        }
    }
}
